services:
  - type: web
    name: stocksense-fastapi
    env: python
    rootDir: fastapi/Scripts
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn stocks.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PROJECT_URL
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: mail
        sync: false
      - key: password
        sync: false
